## Geometry analysis-Homework


In [1]:
import os
import numpy

file_location = os.path.join('data', 'water.xyz')
xyz_file = numpy.genfromtxt(fname=file_location, dtype='unicode', skip_header=2)

In [2]:
print(xyz_file)

[['O' '0.000000' '-0.007156' '0.965491']
 ['H1' '-0.000000' '0.001486' '-0.003471']
 ['H2' '0.000000' '0.931026' '1.207929']]


In [4]:
symbols = xyz_file[:,0]
coordinates = xyz_file[:,1:]
coordinates = coordinates.astype(numpy.float)

In [5]:
print(symbols)
print(coordinates)

['O' 'H1' 'H2']
[[ 0.       -0.007156  0.965491]
 [-0.        0.001486 -0.003471]
 [ 0.        0.931026  1.207929]]


In [20]:
num_atoms = len(symbols)

for i in range(0,num_atoms):
    for j in range(0, num_atoms):
        if i>j:
            x_distance = coordinates[i,0]- coordinates[j,0]
            y_distance = coordinates[i,1]- coordinates[j,1]
            z_distance = coordinates[i,2]- coordinates[j,2]
            distance = numpy.sqrt(x_distance**2 + y_distance**2 + z_distance**2)
            if distance < 1.5 and distance> 0  :  
                #print(i,j)
                print(F'{symbols[i]} to {symbols[j]} : {distance:.3f}')

H1 to O : 0.969
H2 to O : 0.969


## Writing and Using Functions


In [21]:
#def function_name(parameters):
    #** body of your function **
    #** write code using the parameters to calculate something **
    #return value_to_return

In [27]:
def calculate_distance(coords1, coords2):
    x_distance = coords1[0] - coords2[0]
    y_distance = coords1[1] - coords2[1]
    z_distance = coords1[2] - coords2[2]
    distance = numpy.sqrt(x_distance**2 +y_distance**2 + z_distance**2)
    return distance

# calculate_distance([0,0,0], [0,0,1])

In [28]:
calculate_distance([0,0,0],[0,0,1])

1.0

In [29]:
num_atoms = len(symbols)

for i in range(0,num_atoms):
    for j in range(0, num_atoms):
        if i>j:
            distance = calculate_distance(coordinates[i], coordinates[j])
            if bond_check(distance) is True:  
                #print(i,j)
                print(F'{symbols[i]} to {symbols[j]} : {distance:.3f}')

H1 to O : 0.969
H2 to O : 0.969


In [31]:
# Write a function to check and see if a distance is a bond
def bond_check(atom_distance):
    if atom_distance > 0 and atom_distance < 1.5:
        return True
    else:
        return False
    

In [32]:
bond_check(1.7)

False

In [33]:
bond_check(1.2)

True

In [42]:
# Modify the bond check function to take a minimum and a maximum length as an input
def bond_check(atom_distance):
    minimum = float(input('minimum:'))
    maximum = float(input('maximum:'))
    if atom_distance > minimum and atom_distance < maximum:
        return True
    else:
        return False
    

In [43]:
bond_check(1.2)

minimum:0
maximum:1.5


True

In [50]:
#alternitively
def bond_check(atom_distance, minimum=0, maximum=1.5):
    """
    Checks if adistanc eis abond based on a minimum and a maximum
    Inputs: distance, minimum length for bond, maximum length for bond
    Default: minimum: 0 angstroms, maximum: 1.5 angstroms
    """
    if atom_distance > minimum and atom_distance < maximum:
        return True
    else:
        return False

In [47]:
bond_check(1.2,0,1.5)

True

In [48]:
bond_check(1.2)

True

In [49]:
num_atoms = len(symbols)

for i in range(0,num_atoms):
    for j in range(0, num_atoms):
        if i>j:
            distance = calculate_distance(coordinates[i], coordinates[j])
            if bond_check(distance) is True:  
                #print(i,j)
                print(F'{symbols[i]} to {symbols[j]} : {distance:.3f}')

H1 to O : 0.969
H2 to O : 0.969


In [51]:
help(bond_check)

Help on function bond_check in module __main__:

bond_check(atom_distance, minimum=0, maximum=1.5)
    Checks if adistanc eis abond based on a minimum and a maximum
    Inputs: distance, minimum length for bond, maximum length for bond
    Default: minimum: 0 angstroms, maximum: 1.5 angstroms



In [52]:
# Write a new function called open_xyz that opens and process an xyz file. Your function 
# should accept a filepath for the input. 


def open_xyz(filename):
    
    """
    This function opens a standard xyz file.
    It returns the symbols as strings and the coordinates as floats.
    """
    xyz_file = numpy.genfromtxt(fname=filename, skip_header=2, dtype='unicode')
    symbols = xyz_file[:,0]
    coord = xyzfile[:,1:]
    coord = coord.astype(numpy.float)
    return symbols, coord


In [61]:
import os
import numpy

def calculate_distance(coords1, coords2):
    x_distance = coords1[0] - coords2[0]
    y_distance = coords1[1] - coords2[1]
    z_distance = coords1[2] - coords2[2]
    distance = numpy.sqrt(x_distance**2 +y_distance**2 + z_distance**2)
    return distance

def bond_check(atom_distance, minimum=0, maximum=1.5):
    """
    Checks if adistanc eis abond based on a minimum and a maximum
    Inputs: distance, minimum length for bond, maximum length for bond
    Default: minimum: 0 angstroms, maximum: 1.5 angstroms
    """
    if atom_distance > minimum and atom_distance < maximum:
        return True
    else:
        return False
    
def open_xyz(filename):
    
    """
    This function opens a standard xyz file.
    It returns the symbols as strings and the coordinates as floats.
    """
    xyz_file = numpy.genfromtxt(fname=filename, skip_header=2, dtype='unicode')
    symbols = xyz_file[:,0]
    coord = xyz_file[:,1:]
    coord = coord.astype(numpy.float)
    return symbols, coord


file_location = os.path.join('data', 'water.xyz')
symbols, coord = open_xyz(file_location)
num_atoms = len(symbols)
for num1 in range(0,num_atoms):
    for num2 in range(0,num_atoms):
        if num1<num2:
            distance = calculate_distance(coord[num1], coord[num2])
            if bond_check(distance) is True:
                print(F'{symbols[num1]} to {symbols[num2]} : {distance:.3f}')
    
    
    
    
    
    
    
    
    

O to H1 : 0.969
O to H2 : 0.969
